import { MigrationInterface, QueryRunner } from "typeorm";

export class AddUnitOrigin1791481520112 implements MigrationInterface {
    name = 'AddUnitOrigin1791481520112'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "unit_repeaters" DROP CONSTRAINT "FK_unit_repeaters_unit"`);
        await queryRunner.query(`ALTER TABLE "unit_repeaters" DROP CONSTRAINT "FK_unit_repeaters_repeater"`);
        await queryRunner.query(`ALTER TABLE "units" DROP CONSTRAINT "FK_units_client"`);
        await queryRunner.query(`ALTER TABLE "user_sessions" DROP CONSTRAINT "FK_user_sessions_user"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_audit_logs_user"`);
        await queryRunner.query(`ALTER TABLE "report_exports" DROP CONSTRAINT "FK_report_exports_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_units_clientId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_transmissions_createdAt"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_transmissions_unitId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_transmissions_repeaterId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_transmissions_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_users_role"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_users_active"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_logs_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_logs_action"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_logs_createdAt"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_report_exports_userId"`);
        await queryRunner.query(`ALTER TABLE "detected_units" DROP COLUMN "firstSeenAt"`);
        await queryRunner.query(`ALTER TABLE "detected_units" DROP COLUMN "lastSeenAt"`);
        await queryRunner.query(`ALTER TABLE "detected_units" DROP COLUMN "totalMessages"`);
        await queryRunner.query(`ALTER TABLE "detected_units" DROP COLUMN "linked"`);
        await queryRunner.query(`ALTER TABLE "positions" DROP COLUMN "unitId"`);
        await queryRunner.query(`ALTER TABLE "positions" DROP COLUMN "heading"`);
        await queryRunner.query(`ALTER TABLE "positions" DROP COLUMN "accuracy"`);
        await queryRunner.query(`ALTER TABLE "positions" DROP COLUMN "rawData"`);
        await queryRunner.query(`ALTER TABLE "raw_messages" DROP COLUMN "rawData"`);
        await queryRunner.query(`ALTER TABLE "raw_messages" DROP COLUMN "receivedAt"`);
        await queryRunner.query(`ALTER TABLE "units" ADD "origin" character varying NOT NULL DEFAULT 'MANUAL'`);
        await queryRunner.query(`ALTER TABLE "detected_units" ADD "firstDetectionAt" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "detected_units" ADD "lastDetectionAt" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "detected_units" ADD "transmissionCount" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "detected_units" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "detected_units" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "positions" ADD "messageId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "positions" ADD "source" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "positions" ADD "deviceId" character varying`);
        await queryRunner.query(`ALTER TABLE "positions" ADD "course" double precision`);
        await queryRunner.query(`ALTER TABLE "positions" ADD "ignition" boolean`);
        await queryRunner.query(`ALTER TABLE "positions" ADD "parameters" json`);
        await queryRunner.query(`ALTER TABLE "positions" ADD "rawMessageId" character varying`);
        await queryRunner.query(`ALTER TABLE "positions" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "raw_messages" ADD "payload" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "raw_messages" ADD "source" character varying`);
        await queryRunner.query(`ALTER TABLE "raw_messages" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "units" ALTER COLUMN "plate" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "detected_units" ADD CONSTRAINT "UQ_128b920623dc379434b67f151a3" UNIQUE ("imei")`);
        await queryRunner.query(`ALTER TABLE "positions" ALTER COLUMN "receivedAt" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "positions" ALTER COLUMN "latitude" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "positions" ALTER COLUMN "longitude" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transmissions" DROP COLUMN "unitId"`);
        await queryRunner.query(`ALTER TABLE "transmissions" ADD "unitId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transmissions" DROP COLUMN "repeaterId"`);
        await queryRunner.query(`ALTER TABLE "transmissions" ADD "repeaterId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transmissions" DROP COLUMN "positionId"`);
        await queryRunner.query(`ALTER TABLE "transmissions" ADD "positionId" character varying`);
        await queryRunner.query(`ALTER TABLE "transmissions" DROP COLUMN "rawMessageId"`);
        await queryRunner.query(`ALTER TABLE "transmissions" ADD "rawMessageId" character varying`);
        await queryRunner.query(`CREATE INDEX "IDX_e023fd28abf62510908512680f" ON "positions"  ("imei") `);
        await queryRunner.query(`CREATE INDEX "IDX_c253d7ef4b2bb7b82e0e5b89ce" ON "positions"  ("eventTime") `);
        await queryRunner.query(`CREATE INDEX "IDX_ea1be6b4cfde832b7f2813e461" ON "positions"  ("receivedAt") `);
        await queryRunner.query(`ALTER TABLE "unit_repeaters" ADD CONSTRAINT "FK_726156a8b6732b19735f15c52c5" FOREIGN KEY ("unitId") REFERENCES "units"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unit_repeaters" ADD CONSTRAINT "FK_961f681b729f21ca2a0ed5a67bb" FOREIGN KEY ("repeaterId") REFERENCES "repeaters"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "units" ADD CONSTRAINT "FK_400d8aa737858df971982b18586" FOREIGN KEY ("clientId") REFERENCES "clients"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_sessions" ADD CONSTRAINT "FK_55fa4db8406ed66bc7044328427" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_cfa83f61e4d27a87fcae1e025ab" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_exports" ADD CONSTRAINT "FK_4efd1e1bc14b769bed8dac7192f" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "report_exports" DROP CONSTRAINT "FK_4efd1e1bc14b769bed8dac7192f"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_cfa83f61e4d27a87fcae1e025ab"`);
        await queryRunner.query(`ALTER TABLE "user_sessions" DROP CONSTRAINT "FK_55fa4db8406ed66bc7044328427"`);
        await queryRunner.query(`ALTER TABLE "units" DROP CONSTRAINT "FK_400d8aa737858df971982b18586"`);
        await queryRunner.query(`ALTER TABLE "unit_repeaters" DROP CONSTRAINT "FK_961f681b729f21ca2a0ed5a67bb"`);
        await queryRunner.query(`ALTER TABLE "unit_repeaters" DROP CONSTRAINT "FK_726156a8b6732b19735f15c52c5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ea1be6b4cfde832b7f2813e461"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c253d7ef4b2bb7b82e0e5b89ce"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e023fd28abf62510908512680f"`);
        await queryRunner.query(`ALTER TABLE "transmissions" DROP COLUMN "rawMessageId"`);
        await queryRunner.query(`ALTER TABLE "transmissions" ADD "rawMessageId" uuid`);
        await queryRunner.query(`ALTER TABLE "transmissions" DROP COLUMN "positionId"`);
        await queryRunner.query(`ALTER TABLE "transmissions" ADD "positionId" uuid`);
        await queryRunner.query(`ALTER TABLE "transmissions" DROP COLUMN "repeaterId"`);
        await queryRunner.query(`ALTER TABLE "transmissions" ADD "repeaterId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transmissions" DROP COLUMN "unitId"`);
        await queryRunner.query(`ALTER TABLE "transmissions" ADD "unitId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "positions" ALTER COLUMN "longitude" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "positions" ALTER COLUMN "latitude" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "positions" ALTER COLUMN "receivedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "detected_units" DROP CONSTRAINT "UQ_128b920623dc379434b67f151a3"`);
        await queryRunner.query(`ALTER TABLE "units" ALTER COLUMN "plate" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "raw_messages" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "raw_messages" DROP COLUMN "source"`);
        await queryRunner.query(`ALTER TABLE "raw_messages" DROP COLUMN "payload"`);
        await queryRunner.query(`ALTER TABLE "positions" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "positions" DROP COLUMN "rawMessageId"`);
        await queryRunner.query(`ALTER TABLE "positions" DROP COLUMN "parameters"`);
        await queryRunner.query(`ALTER TABLE "positions" DROP COLUMN "ignition"`);
        await queryRunner.query(`ALTER TABLE "positions" DROP COLUMN "course"`);
        await queryRunner.query(`ALTER TABLE "positions" DROP COLUMN "deviceId"`);
        await queryRunner.query(`ALTER TABLE "positions" DROP COLUMN "source"`);
        await queryRunner.query(`ALTER TABLE "positions" DROP COLUMN "messageId"`);
        await queryRunner.query(`ALTER TABLE "detected_units" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "detected_units" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "detected_units" DROP COLUMN "transmissionCount"`);
        await queryRunner.query(`ALTER TABLE "detected_units" DROP COLUMN "lastDetectionAt"`);
        await queryRunner.query(`ALTER TABLE "detected_units" DROP COLUMN "firstDetectionAt"`);
        await queryRunner.query(`ALTER TABLE "units" DROP COLUMN "origin"`);
        await queryRunner.query(`ALTER TABLE "raw_messages" ADD "receivedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "raw_messages" ADD "rawData" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "positions" ADD "rawData" json`);
        await queryRunner.query(`ALTER TABLE "positions" ADD "accuracy" double precision`);
        await queryRunner.query(`ALTER TABLE "positions" ADD "heading" double precision`);
        await queryRunner.query(`ALTER TABLE "positions" ADD "unitId" uuid`);
        await queryRunner.query(`ALTER TABLE "detected_units" ADD "linked" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "detected_units" ADD "totalMessages" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "detected_units" ADD "lastSeenAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "detected_units" ADD "firstSeenAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "IDX_report_exports_userId" ON "report_exports" USING btree ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_logs_createdAt" ON "audit_logs" USING btree ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_logs_action" ON "audit_logs" USING btree ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_logs_userId" ON "audit_logs" USING btree ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_users_active" ON "users" USING btree ("active") `);
        await queryRunner.query(`CREATE INDEX "IDX_users_role" ON "users" USING btree ("role") `);
        await queryRunner.query(`CREATE INDEX "IDX_transmissions_status" ON "transmissions" USING btree ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_transmissions_repeaterId" ON "transmissions" USING btree ("repeaterId") `);
        await queryRunner.query(`CREATE INDEX "IDX_transmissions_unitId" ON "transmissions" USING btree ("unitId") `);
        await queryRunner.query(`CREATE INDEX "IDX_transmissions_createdAt" ON "transmissions" USING btree ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_units_clientId" ON "units" USING btree ("clientId") `);
        await queryRunner.query(`ALTER TABLE "report_exports" ADD CONSTRAINT "FK_report_exports_user" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_audit_logs_user" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_sessions" ADD CONSTRAINT "FK_user_sessions_user" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "units" ADD CONSTRAINT "FK_units_client" FOREIGN KEY ("clientId") REFERENCES "clients"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unit_repeaters" ADD CONSTRAINT "FK_unit_repeaters_repeater" FOREIGN KEY ("repeaterId") REFERENCES "repeaters"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unit_repeaters" ADD CONSTRAINT "FK_unit_repeaters_unit" FOREIGN KEY ("unitId") REFERENCES "units"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
